# Generated by Django 4.2.7 on 2026-01-27 15:47

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Aircraft model designation (e.g., A320, B777, ATR-72)', max_length=50, unique=True)),
                ('manufacturer', models.CharField(help_text='Aircraft manufacturer (e.g., Airbus, Boeing, ATR)', max_length=100)),
                ('total_capacity', models.IntegerField(help_text='Total passenger capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('economy_capacity', models.IntegerField(default=0, help_text='Economy class seats (for future use)', validators=[django.core.validators.MinValueValidator(0)])),
                ('business_capacity', models.IntegerField(default=0, help_text='Business class seats (for future use)', validators=[django.core.validators.MinValueValidator(0)])),
                ('first_class_capacity', models.IntegerField(default=0, help_text='First class seats (for future use)', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(help_text='IATA three-letter airport code (e.g., DUB, ORK, SNN)', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Europe/Dublin', help_text='Timezone for local time conversions (e.g., Europe/Dublin)', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic coordinates (longitude, latitude)', srid=4326)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoadFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('short_haul', 'Short Haul'), ('long_haul', 'Long Haul'), ('regional', 'Regional')], help_text='Type of route (short_haul, long_haul, regional)', max_length=20)),
                ('season', models.CharField(choices=[('all_year', 'All Year'), ('summer', 'Summer'), ('winter', 'Winter')], default='all_year', help_text='Season for this load factor', max_length=20)),
                ('airline', models.CharField(blank=True, default='', help_text='Specific airline (blank for default)', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Load factor as decimal (e.g., 0.84 for 84%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_default', models.BooleanField(default=False, help_text='Flag indicating this is a fallback default value')),
                ('source', models.CharField(help_text="Data source (e.g., 'IATA 2024-2025')", max_length=200)),
            ],
            options={
                'verbose_name': 'Load Factor',
                'verbose_name_plural': 'Load Factors',
                'ordering': ['route_type', 'season', 'airline'],
                'unique_together': {('route_type', 'season', 'airline')},
            },
        ),
        migrations.CreateModel(
            name='PassengerHeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Timestamp of this data point')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('passenger_count', models.IntegerField(help_text='Passenger count at this location/time', validators=[django.core.validators.MinValueValidator(0)])),
                ('airport', models.ForeignKey(help_text='Associated airport', on_delete=django.db.models.deletion.CASCADE, to='core.airport')),
            ],
            options={
                'verbose_name': 'Passenger Heatmap Data',
                'verbose_name_plural': 'Passenger Heatmap Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['airport', 'timestamp'], name='core_passen_airport_42e22e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PassengerEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of estimate')),
                ('hour', models.IntegerField(help_text='Hour of day (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('passenger_count', models.IntegerField(help_text='Estimated passenger count for this hour', validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_score', models.FloatField(help_text='Average confidence score for this hour (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this estimate was computed')),
                ('airport', models.ForeignKey(help_text='Airport for this estimate', on_delete=django.db.models.deletion.CASCADE, to='core.airport')),
            ],
            options={
                'verbose_name': 'Passenger Estimate',
                'verbose_name_plural': 'Passenger Estimates',
                'ordering': ['airport', 'date', 'hour'],
                'indexes': [models.Index(fields=['airport', 'date'], name='core_passen_airport_2fb3a5_idx')],
                'unique_together': {('airport', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Flight number (e.g., EI101, BA832)', max_length=10)),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure time (local airport time)')),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival time (local airport time)')),
                ('airline', models.CharField(help_text='Operating airline', max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('departed', 'Departed'), ('arrived', 'Arrived')], default='scheduled', help_text='Current flight status', max_length=20)),
                ('estimated_passengers', models.IntegerField(blank=True, help_text='Estimated passenger count (computed by algorithm)', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score 0.0-1.0 (computed by algorithm)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(blank=True, help_text='Aircraft type (null triggers intelligent defaults)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aircrafttype')),
                ('destination', models.ForeignKey(help_text='Arrival airport', on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.airport')),
                ('origin', models.ForeignKey(help_text='Departure airport', on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.airport')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['origin', 'departure_time'], name='core_flight_origin__784bc4_idx'), models.Index(fields=['destination', 'arrival_time'], name='core_flight_destina_ff487b_idx'), models.Index(fields=['status'], name='core_flight_status_bd9e25_idx')],
            },
        ),
    ]
