# Generated by Django 4.2.7 on 2026-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, help_text="Departure gate (e.g., '114', '211') — drives zone intensity in heatmap", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='terminal',
            field=models.CharField(blank=True, help_text="Departure terminal (e.g., '1', '2') — used for gate-driven heatmap in Phase 3D", max_length=10, null=True),
        ),
    ]
